# Specify the Dart SDK base image version using dart:<version> (ex: dart:2.12)
#FROM dart:stable AS build
# FROM ubuntu:21.04 AS build
FROM google/dart as build

ENV TZ=Australia/Melbourne 
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone RUN dpkg-reconfigure -f noninteractive tzdata

RUN mkdir /src
WORKDIR /src

RUN mkdir -p /BUILD_TOKEN/ae5079337c374035aa65f468d04a1afd
COPY . /src/batman

WORKDIR /src/batman

RUN mkdir /batman
RUN dart pub get
RUN dart compile exe /src/batman/bin/batman.dart -o /batman/batman


# Build minimal  image from AOT-compiled `/batman`
FROM build
COPY --from=build /batman/batman /batman/batman

WORKDIR /
RUN mkdir /etc/batman
WORKDIR /batman
RUN ./batman install --db_path=/data/hive --rule_path=/etc/batman/batman.yaml

# schedule scans.
ENTRYPOINT ["nice", "-n", "19", "./batman", "--quiet", "--no-colour", "cron","30 22 * * * *"]

# remove the ENTRYPOINT and uncomment this line to enable interactive debugging.
# CMD ["bash"]
