#! /usr/bin/env dcli

import 'package:batman/src/version/version.g.dart';

// ignore: prefer_relative_imports
import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create docker_push.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) {
  final projectRoot = DartProject.self.pathToProjectRoot;
  final dockerfilePath = join(projectRoot, 'docker', 'Dockerfile');

  final tag = 'noojee/batman:$packageVersion';
  final latest = 'noojee/batman:latest';

  'docker  build -t $tag -t $latest -f $dockerfilePath .'.run;
  'docker push noojee/batman:$packageVersion'.run;
  'docker push $tag'.run;
  'docker push $latest'.run;
}
