#! /usr/bin/env dcli

import 'dart:io';

import 'package:args/args.dart';
import 'package:batman/src/version/version.g.dart';

// ignore: prefer_relative_imports
import 'package:dcli/dcli.dart';

/// dcli script generated by:
/// dcli create docker_push.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) {
  final projectRoot = DartProject.self.pathToProjectRoot;
  final dockerfilePath = join(projectRoot, 'docker', 'DockerFile');

  'docker -f $dockerfilePath build '.run;
  'docker push noojee/batman:$packageVersion'.run;
}
