#! /usr/bin/env dcli
/* Copyright (C) S. Brett Sutton - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Brett Sutton <bsutton@onepub.dev>, Jan 2022
 */

// ignore: prefer_relative_imports
import 'package:batman/src/hive/model/file_checksum.dart';

/// dcli script generated by:
/// dcli create checksum.dart
///
/// See
/// https://pub.dev/packages/dcli#-installing-tab-
///
/// For details on installing dcli.
///

void main(List<String> args) async {
  print(DateTime.now());
  await FileChecksum.contentChecksum(
      '/home/bsutton/git/batman.bak/batman/test/sample_logs/njcontact.log');
  print(DateTime.now());
}
